name: rivil
description: A Flutter app for discovering tourist destinations in Malang
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Supabase
  supabase_flutter: ^2.9.0

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Storage
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5

  # UI
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.1.0
  lottie: ^3.3.1

  # Location
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  google_maps_flutter: ^2.12.1
  url_launcher: ^6.3.1

  # Artificial Intelligence
  google_generative_ai: ^0.4.7
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/destinations/
    - assets/vectors/
    - .env

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
