final List<Map<String, dynamic>> allDestinations = [
  {
    'name': 'Gunung Bromo',
    'location': 'Malang, Indonesia',
    'price': 25000,
    'distance': 32.5,
    'rating': 4.8,
    'imageUrl': 'assets/images/bromo-image.jpg',
    'facilities': [
      'Parkir',
      'Toilet',
      'Warung Makan',
      'Penginapan',
      'Spot Foto'
    ],
    'isFavorite': true,
    'category': 'Gunung',
  },
  {
    'name': 'Pantai Malang Selatan',
    'location': 'Malang, Indonesia',
    'price': 10000,
    'distance': 45.7,
    'rating': 4.7,
    'imageUrl': 'assets/images/bromo-image.jpg',
    'facilities': ['Parkir', 'Toilet', 'Warung Makan', 'Spot Foto'],
    'isFavorite': false,
    'category': 'Pantai',
  },
  {
    'name': 'Museum Angkut',
    'location': 'Batu, Indonesia',
    'price': 100000,
    'distance': 15.2,
    'rating': 4.6,
    'imageUrl': 'assets/images/bromo-image.jpg',
    'facilities': [
      'Parkir',
      'Toilet',
      'Musholla',
      'Warung Makan',
      'Wifi',
      'Spot Foto'
    ],
    'isFavorite': true,
    'category': 'Museum',
  },
  {
    'name': 'Coban Rondo',
    'location': 'Malang, Indonesia',
    'price': 20000,
    'distance': 28.9,
    'rating': 4.5,
    'imageUrl': 'assets/images/bromo-image.jpg',
    'facilities': ['Parkir', 'Toilet', 'Warung Makan', 'Spot Foto'],
    'isFavorite': false,
    'category': 'Air Terjun',
  },
  {
    'name': 'Jatim Park',
    'location': 'Malang, Indonesia',
    'price': 150000,
    'distance': 18.3,
    'rating': 4.6,
    'imageUrl': 'assets/images/bromo-image.jpg',
    'facilities': [
      'Parkir',
      'Toilet',
      'Musholla',
      'Warung Makan',
      'Wifi',
      'Spot Foto'
    ],
    'isFavorite': false,
    'category': 'Taman',
  },
];
